- name: Create Custom Network
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
   - name: Create networks
     gce_net:
        name: awx-custom
        mode: custom
        subnet_name: "awx-east"
        subnet_region: us-east1
        ipv4_range: '10.240.16.0/24'
        state: "present"

   - name: Create second subnet
     gce_net:   
        name: awx-custom
        subnet_name: "awx-west"
        subnet_region: us-west1
        ipv4_range: '10.240.14.0/24'
        state: "present"